name = "ColorSchemes"
uuid = "35d6a980-a343-548e-a6ea-1d62b119f2f4"
authors = ["cormullion", "rafaqz", "gustaphe", "lwabeke", "NHDaly", "stevengj", "t-bltg", "asinghvi17", "davibarreira", "adrhill", "tecosaur", "jarredclloyd"]
version = "3.31.0"

[deps]
ColorTypes = "3da002f7-5984-5a60-b8a6-cbb66c0b333f"
ColorVectorSpace = "c3611d14-8923-5661-9e6a-0046d554d3a4"
Colors = "5ae59095-9a9b-59fe-a467-6f913c188581"
FixedPointNumbers = "53c48c17-4a7d-5ca2-90c5-79b7896eea93"
PrecompileTools = "aea7be01-6a6a-4083-8856-8a6e6704d82a"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"

[compat]
ColorTypes = "0.11, 0.12, 0.12.1"
ColorVectorSpace = "0.10, 0.11"
Colors = "0.12, 0.13, 0.13.1"
FixedPointNumbers = "0.8, 0.8.5"
PrecompileTools = "1"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
